num1 = (input('Digite algo '))
print('Qual é o tipo primitivo do valor -{}-?'.format(num1), type(num1))
print('O valor -{}- é numérico?'.format(num1), num1.isnumeric())
print('O valor -{}- é alfabético?'.format(num1), num1.isalpha())
print('O valor -{}- é alfanumérico?'.format(num1), num1.isalnum())
print('O valor -{}- só tem espaços?'.format(num1), num1.isspace())
print('O valor -{}- só possui letrar minúsculas?'.format(num1), num1.islower())
print('O valor -{}- só possui letrar maiúsculas?'.format(num1), num1.isupper())
print('O valor -{}- está capitalizado?'.format(num1), num1.istitle())
